### ISSUE TITLE
Marks not provided for Deepak Kumar who was part of the team.

### ISSUE THREAD

**Issue by dhanush-ai1990** [InfoVizW2018/activity-2-medd#1]
There were four students on our team- Dhanush, ED, Maryam and Deepak Kumar. Marks assigned as 0 for Deepak Kumar who made equal contributions to this activity. I can see that his name is not showing up in the contribution chat, and that might have caused this confusion and also we haven't mentioned it anywhere as well.

The 4 Students in the group was consulted with Peggy.

**Comment by davidsjohnson** [comment]
Thanks for letting me know.  There we no names in the submission so I had no way to know everyone in the group.  We'll get this updated.

Thanks!

**Comment by dhanush-ai1990** [comment]
The issue has been brought to the attention of the TA. Closing for now :)
